baseURL: https://buraglio.com/
languageCode: en-us
title: buraglio.com
theme: freshstart

params:
  author: Nick Buraglio
  description: Random crap that updates infrequently
  favicon: /favicon.ico


  searchEngines:
    - name: Google
      activated: true
      icon: fab fa-google
      url: https://google.com/search
    - name: DuckDuckGo
      activated: true
      icon: fas fa-search
      url: https://www.duckduckgo.com


   nav:
  #  - name: email
  #    icon: fas fa-envelope red
  #    url: https://mail.google.com

    - name: Twitter
      icon: fab fa-twitter aqua
      url: https://twitter.com/forwardingplane
    

  bookmarks:
    - group: links
      icon: fas fa-code-branch
      items:
        - name: webmail
          url: https://mail.google.com/
        - name: calendar
          url: https://calendar.google.com
        - name: drive
          #icon: fab fa-github
          url: https://drive.google.com
        #- name: gitlab
        #  icon: fab fa-gitlab
        #  url: https://gitlab.com

