baseURL: https://buraglio.com/
languageCode: en-us
title: buraglio.com
theme: freshstart

params:
  author: Nick Buraglio
  description: Random crap that updates infrequently
  favicon: /favicon.ico


  searchEngines:
    - name: Google
      activated: true
      icon: fab fa-google
      url: https://google.com/search
    - name: DuckDuckGo
      activated: true
      icon: fas fa-search
      url: https://www.duckduckgo.com
    - name: Bing
      activated: true
      icon: fas fa-search
      url: https://www.bing.com

  nav:
  #  - name: email
  #    icon: fas fa-envelope red
  #    url: https://mail.google.com

#    - name: Bluesky
     #  icon: fab fa-twitter aqua
#      url: https://bsky.app/profile/forwardingplane.net
  #  - name: Mastodon
     #  icon: fab fa-twitter aqua
 #     url: https://dial.modem.show/@forwardingplane@dial.modem.show
   # - name: TeePublic Store
    #  icon: fab fa-twitter aqua
    #  url: https://www.teepublic.com/user/cinematic-omelete-studios
    #- name: Technical Blog
    #  icon: fab fa-twitter aqua
    #  url: https://www.forwardingplane.net

  bookmarks:
    - group: links
      icon: fas fa-code-branch
      items:
        - name: Webmail
          url: https://mail.google.com/
        - name: Calendar
          url: https://calendar.google.com
        - name: Drive
          #icon: fab fa-github
          url: https://drive.google.com
        - name: photos
        #  icon: fab fa-gitlab
          url: https://pictures.google.com
        - name: news
        #  icon: fab fa-gitlab
          url: https://news.google.com
        - name: GitHub
          icon: fab fa-github
          url: https://github.com/buraglio
        - name: Bluesky
          #  icon: fab fa-twitter aqua
          url: https://bsky.app/profile/forwardingplane.net
        - name: Mastodon
          #  icon: fab fa-twitter aqua
          url: https://dial.modem.show/@forwardingplane@dial.modem.show
        - name: TeePublic Store
          #  icon: fab fa-twitter aqua
          url: https://www.teepublic.com/user/cinematic-omelete-studios
        - name: Technical Blog
          #  icon: fab fa-twitter aqua
          url: https://www.forwardingplane.net
